version: '3.7'

volumes:
  node_modules:

services:
  dofuslab:
    image: cobelt/dofuslab
    container_name: dofuslab_frontend

    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/app
    - node_modules:/app/dofuslab/node_modules

    ports:
    - '3051:80'

    environment:
    - NODE_ENV=development

    command: yarn start