version: '3.7'

volumes:
  node_modules:

services:
  shokkoth:
    build:
      context: .
    ports:
      - '3000:3000'

    environment:
      - NODE_ENV=production
      - PORT=3000

    networks:
      - shokkoth-universe

networks:
  shokkoth-universe:
    external:
        name: shokkoth-universe
