version: '3.7'

volumes:
  node_modules:

services:
  shokkoth:
    build:
      context: .
    ports:
      - '3051:80'

    environment:
      - NODE_ENV=development

    networks:
      - shokkoth-universe

networks:
  shokkoth-universe:
    external:
        name: shokkoth-universe
