version: '3.7'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017

    volumes:
      - /data/db:/backup
    networks:
      - shokkoth-universe

networks:
  shokkoth-universe:
    name: shokkoth-universe
    driver: bridge
