version: '3.7'
services:
  api:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_SERVER=mongodb
      - MONGO_PORT=27017
      - PORT=5000
    networks:
      - shokkoth-universe

networks:
  shokkoth-universe:
    external:
        name: shokkoth-universe
